name: Hangul Platypus

options:
  deploymentTarget:
    iOS: "14.0"
    macOS: "11.0"
  developmentLanguage: ko
  preGenCommand: mv Hangul\ Platypus.xcodeproj/xcshareddata/xcschemes/ .
  postGenCommand: mv xcschemes/ Hangul\ Platypus.xcodeproj/xcshareddata/

settings:
  PRODUCT_BUNDLE_IDENTIFIER: dev.sboh.hangul-editor
  MARKETING_VERSION: "0.1.0"
  CURRENT_PROJECT_VERSION: 2
  CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES

targets:
  Hangul Platypus (iOS):
    type: application
    platform: iOS
    sources: [Shared, iOS]
    dependencies:
      - package: CoreHwp
    info:
      path: iOS/Info.plist
      properties:
        CFBundleDocumentTypes:
          - CFBundleTypeName: HWP
            LSHandlerRank: Alternate
            LSItemContentTypes:
            - kr.co.hancom.hwp
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleURLTypes: []
        LSRequiresIPhoneOS: true # Disable macOS catalyst
        LSSupportsOpeningDocumentsInPlace: true
        UIAppFonts:
          - HANBatang.ttf
          - HANBatangB.ttf
          - HANDotum.ttf
          - HANDotumB.ttf
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true # iPadOS multi windows
        UIApplicationSupportsIndirectInputEvents: true # iPadOS mouse event
        UILaunchScreen: {} # SwiftUI Default
        UIRequiredDeviceCapabilities:
          - armv7 # SwiftUI Default
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportsDocumentBrowser: true
        UTImportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Hanword Document
            UTTypeIdentifier: kr.co.hancom.hwp
            UTTypeTagSpecification:
              public.filename-extension:
                - hwp
    preBuildScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi

  Hangul Platypus (macOS):
    type: application
    platform: macOS
    sources: [Shared, macOS]
    settings:
      CODE_SIGN_IDENTITY: "-"
    dependencies:
      - package: CoreHwp
    info:
      path: macOS/Info.plist
      properties:
        ATSApplicationFontsPath: "."
        CFBundleDocumentTypes:
          - CFBundleTypeName: Hancom Word Document
            CFBundleTypeRole: Viewer
            LSHandlerRank: Alternate
            LSItemContentTypes:
              - com.haansoft.HancomOfficeViewer.mac.hwp
        CFBundleIconFile: ""
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        LSApplicationCategoryType: public.app-category.productivity
        LSHasLocalizedDisplayName: true
        LSMinimumSystemVersion: $(MACOSX_DEPLOYMENT_TARGET)
        UTImportedTypeDeclarations:
          - UTTypeConformsTo:
              - public.data
            UTTypeDescription: Hancom Word Document
            UTTypeIdentifier: com.haansoft.HancomOfficeViewer.mac.hwp
            UTTypeReferenceURL: http://www.hancom.co.kr/
            UTTypeTagSpecification:
              public.filename-extension:
                - hwp
    entitlements:
      path: macOS/macOS.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-write: true
    preBuildScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
  
  Tests iOS:
    type: bundle.ui-testing
    platform: iOS
    sources: [Tests iOS]

  Tests macOS:
    type: bundle.ui-testing
    platform: macOS
    sources: [Tests macOS]

packages:
  CoreHwp:
    url: https://github.com/sboh1214/Hwp-Swift.git
    exactVersion: 0.14.1
