name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        platform: ["iOS", "macOS"]

    steps:
    - uses: actions/checkout@v2
    - name: Install xcodegen
      run: brew install xcodegen
    - name: Generate xcodeproj
      run: xcodegen generate
    - name: Release Build
      env:
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_ENTITLEMENTS: ""
        CODE_SIGNING_ALLOWED: "NO"
      run: xcodebuild -project Hangul\ Platypus.xcodeproj -scheme Hangul\ Platypus\ \(${{ matrix.platform }}\) -configuration Release --no-codesign
