name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        include:
          - platform: iOS
            scheme: Hangul Platypus
            action: build
          - platform: macOS
            scheme: Hangul Platypus
            action: build

    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1.2.3
      with:
        xcode-version: 13
    - name: Install xcodegen
      run: brew install xcodegen
    - name: Generate xcodeproj
      run: xcodegen generate
    - uses: mxcl/xcodebuild@v1.9.2
      with:
        platform: ${{ matrix.platform }}
        scheme: ${{ matrix.scheme }} (${{ matrix.platform }})
        action: ${{ matrix.action }}
        code-coverage: true
        verbosity: xcpretty
        upload-logs: always
